name: Build Production APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Configuration de JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configuration de Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"
          channel: 'stable'

      - name: Clean Gradle cache
        run: |
          rm -rf ~/.gradle/caches/
          cd android
          ./gradlew clean
          cd ..

      - name: Install dependencies
        run: |
          flutter pub cache repair
          flutter pub upgrade
          cd android
          ./gradlew --refresh-dependencies
          cd ..

      - name: Mise à jour de Gradle vers 8.2
        run: |
          cd android
          ./gradlew wrapper --gradle-version 8.2
          cd ..

      - name: Génération des icônes et écran de démarrage
        run: |
          flutter pub run flutter_launcher_icons
          if grep -q "flutter_native_splash" pubspec.yaml; then
            flutter pub run flutter_native_splash:create
          fi

      - name: Construction de l'APK en mode release
        run: flutter build apk --release --no-tree-shake-icons

      - name: Téléversement de l'APK
        uses: actions/upload-artifact@v4
        with:
          name: dumumtergo-release
          path: build/app/outputs/flutter-apk/app-release.apk
